services:
  db:
    image: postgres:15
    shm_size: 1g
    restart: on-failure
    ports:
      - "5437:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ref
      POSTGRES_PASSWORD: sql
      POSTGRES_DB: ref
  test-db:
    image: postgres:15
    restart: on-failure
    ports:
      - "5438:5432"
    volumes:
      - db-data-test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ref
      POSTGRES_PASSWORD: sql
      POSTGRES_DB: ref_test

volumes:
  db-data:
    driver: local
  db-data-test:
    driver: local
